FROM envirosoftwaresolutions/ubuntu-asdf:0.7.2

LABEL description="ubuntu + erlang"
LABEL runtime="erlang"
LABEL runtime_version="22.0.4"

# latest erlang (right now) is 22.0.4)
RUN /root/.asdf/bin/asdf install erlang 22.0.4
RUN /root/.asdf/bin/asdf global erlang 22.0.4
